### ISSUE TITLE
Error:  AmbigiousMatchException: Multiple IGridCellValueConnector were found

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Contrib#3]
I am seeing this error when "Restoring" content from Dev to local, after installing the NuGet package for this.

> Umbraco.Deploy.Exceptions.AmbigiousMatchException: Multiple IGridCellValueConnector were found for view "/app_plugins/leblender/editors/leblendereditor/leblendereditor.html" : Umbraco.Deploy.Contrib.Connectors.GridCellValueConnectors.LeBlenderGridCellValueConnector, Umbraco.Deploy.GridCellValueConnectors.LeBlenderGridCellValueConnector.
>    at Umbraco.Deploy.GridCellValueConnectors.DefaultGridCellValueConnectorFactory.GetGridCellConnector(String alias)
>    at Umbraco.Deploy.ValueConnectors.GridValueConnector.GetValue(Property property, ICollection`1 dependencies)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.MapProperties(PropertyCollection properties, ICollection`1 dependencies)
>    at Umbraco.Deploy.ServiceConnectors.DocumentConnector.MapVersion(IContent content, ICollection`1 dependencies)
>    at Umbraco.Deploy.ServiceConnectors.DocumentConnector.GetArtifact(GuidUdi udi, IContent content)
>    at Umbraco.Deploy.ServiceConnectors.DocumentConnector.GetArtifact(GuidUdi udi)
>    at Umbraco.Deploy.ServiceConnectors.ServiceConnectorBase`3.Umbraco.Core.Deploy.IServiceConnector.GetArtifact(Udi udi)
>    at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.GetSignatures(IEnumerable`1 udis, CancellationToken token)
>    at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ReviewManifest(Guid sessionId, Manifest manifest)
>    at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ReviewManifestAsync(Guid sessionId, Manifest manifest, CancellationToken token)
>    at Umbraco.Deploy.WorkItems.DeployRestoreWorkItemBase.<NegotiateManifest>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Umbraco.Deploy.WorkItems.TargetRestoreWorkItem.<Proceed>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Umbraco.Deploy.WorkItems.TargetRestoreWorkItem.<ExecuteAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Umbraco.Deploy.WorkItems.TargetRestoreWorkItem.<ExecuteAsync>d__12.MoveNext()

Perhaps there is some sort of conflict with the built-in ValueConnectors (listed here: https://github.com/umbraco/Umbraco.Deploy.ValueConnectors/tree/master/Umbraco.Deploy.ValueConnectors)?

**Comment by hfloyd** [comment]
Hmm... This seems to be resolved when I compile the project and just copy over the dll - Even when including the LeBlender file, so perhaps it just had something to do with the NuGet packaged version.
